#!/usr/bin/env python3
"""Rebuild TCIM's reviewed C interface inventory; never infer support from linking.

Run --check with Clang on a development host. --check-link needs only nm and
the exact object list/binary from make tcim, so HAL-only hosts can run it too.
"""

import argparse
from collections import Counter
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
INPUT = Path("tcim/ds4_tcim_contract.json")
INVENTORY = Path("tcim/ds4_tcim_inventory.json")
STUBS = Path("tcim/ds4_tcim_stubs.inc")
SOURCES = ("ds4_gpu.h", "ds4_gpu_mgpu.h", "ds4_gpu_args.h", "ds4.c")
KINDS = {"IMPLEMENTED_RUNTIME", "PRODUCT_REQUIRED_TODO", "OPTIONAL_FALLBACK",
         "OUT_OF_SCOPE_UNAVAILABLE"}


def fail(message):
    raise ValueError(message)


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            fail(f"duplicate JSON key/symbol: {key}")
        result[key] = value
    return result


def read_json(path):
    return json.loads(path.read_text(), object_pairs_hook=unique_object)


def run(command, root, source=None):
    result = subprocess.run(command, cwd=root, input=source, text=True,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        fail(f"{' '.join(command)} failed:\n{result.stderr.strip()}")
    return result.stdout


def ast_nodes(text):
    # -ast-dump-filter emits adjacent JSON objects rather than one JSON array.
    decoder = json.JSONDecoder()
    position = 0
    while position < len(text):
        while position < len(text) and text[position].isspace():
            position += 1
        if position < len(text):
            node, position = decoder.raw_decode(text, position)
            yield node


def declarations(root, clang):
    command = [clang, "-std=c99", "-D_GNU_SOURCE", "-DDS4_TCIM_BUILD",
               "-fsyntax-only", "-Wno-everything", "-I.", "-Xclang",
               "-ast-dump=json", "-Xclang", "-ast-dump-filter=ds4_gpu_"]
    # ds4.c includes gpu/mgpu and also carries private cross-TU externs. The
    # args TU closes the auto-probe contract without parsing its C provider.
    dumps = [run(command + ["ds4.c"], root),
             run(command + ["-x", "c", "-"], root,
                 '#include "ds4_gpu_args.h"\n')]
    found = {}
    for dump in dumps:
        for node in ast_nodes(dump):
            if node.get("kind") != "FunctionDecl" or node.get("storageClass") == "static":
                continue
            name = node["name"]
            if not name.startswith("ds4_gpu_"):
                continue
            location = node.get("loc", {})
            source = location.get("file", "").removeprefix("./")
            if source not in SOURCES:
                fail(f"{name}: unreviewed declaration source {source!r}")
            if node.get("variadic"):
                fail(f"{name}: variadic interfaces cannot enter the TCIM contract")
            if any(child.get("kind") == "CompoundStmt" for child in node.get("inner", [])):
                fail(f"{name}: unexpected definition in declaration inputs")
            signature = node["type"]["qualType"]
            if signature.endswith("()"):
                fail(f"{name}: old-style unspecified parameter lists are not C prototypes")
            result = signature[:signature.index("(")].strip()
            parameters = [child["type"]["qualType"] for child in node.get("inner", [])
                          if child.get("kind") == "ParmVarDecl"]
            # Do not improvise a declarator for future function pointers/arrays.
            if any(any(char in value for char in "([]") for value in parameters):
                fail(f"{name}: unsupported parameter declarator; extend the generator explicitly")
            item = found.setdefault(name, {"signature": signature, "return_type": result,
                                            "parameters": parameters, "locations": set()})
            if item["signature"] != signature:
                fail(f"{name}: conflicting declarations")
            item["locations"].add((source, location["offset"]))
    for item in found.values():
        counts = Counter(source for source, _ in item.pop("locations"))
        item["declarations"] = dict(sorted(counts.items()))
    return dict(sorted(found.items()))


def render(root, clang):
    policy = read_json(root / INPUT)
    declared = declarations(root, clang)
    missing = declared.keys() - policy.keys()
    extra = policy.keys() - declared.keys()
    if missing or extra:
        fail(f"classification mismatch: missing={sorted(missing)}, extra={sorted(extra)}")
    inventory = []
    stubs = ["/* Generated by tools/gen_tcim_contract.py; edit the reviewed JSON input. */",
             "/* Only LINK_REQUIRED stubs live here; implemented functions are handwritten. */", ""]
    for name, declaration in declared.items():
        entry = policy[name]
        allowed = {"classification", "link_required", "return", "reason"}
        if not isinstance(entry, dict) or entry.keys() - allowed or not {"classification", "link_required", "reason"} <= entry.keys():
            fail(f"{name}: invalid classification fields")
        kind = entry["classification"]
        if kind not in KINDS or type(entry["link_required"]) is not bool:
            fail(f"{name}: invalid classification or link_required")
        if not isinstance(entry["reason"], str) or not entry["reason"].strip() or "*/" in entry["reason"]:
            fail(f"{name}: a reviewed reason is required")
        generated = entry["link_required"] and kind != "IMPLEMENTED_RUNTIME"
        returns_void = declaration["return_type"] == "void"
        fallback = entry.get("return")
        if kind == "IMPLEMENTED_RUNTIME":
            if fallback is not None:
                fail(f"{name}: handwritten implementation cannot specify a stub return")
        elif returns_void:
            if generated and (kind != "OPTIONAL_FALLBACK" or fallback != "noop"):
                fail(f"{name}: linked void API requires a reviewed safe optional no-op")
            if fallback not in (None, "noop"):
                fail(f"{name}: invalid void return")
        elif fallback not in ("0", "1", "-1", "NULL"):
            fail(f"{name}: explicit existing-contract failure/fallback return is required")
        if not returns_void and declaration["return_type"].endswith("*"):
            if kind != "IMPLEMENTED_RUNTIME" and fallback != "NULL":
                fail(f"{name}: pointer stubs must return NULL")
        elif fallback == "NULL":
            fail(f"{name}: NULL is only valid for pointer stubs")
        inventory.append({"symbol": name, "signature": declaration["signature"],
                          "declarations": declaration["declarations"],
                          "linkage": "LINK_REQUIRED" if entry["link_required"] else "NOT_LINK_REQUIRED",
                          **{key: value for key, value in entry.items() if key != "link_required"},
                          "generated_stub": generated})
        if not generated:
            continue
        parameters = [f"{value} arg{index}" for index, value in enumerate(declaration["parameters"])]
        stubs.append(f"/* {kind}: {entry['reason']} */")
        stubs.append(f"{declaration['return_type']} {name}({', '.join(parameters) or 'void'})")
        stubs.append("{")
        for index in range(len(parameters)):
            stubs.append(f"    (void)arg{index};")
        if kind in ("PRODUCT_REQUIRED_TODO", "OUT_OF_SCOPE_UNAVAILABLE"):
            error = "ENOSYS" if kind == "PRODUCT_REQUIRED_TODO" else "ENOTSUP"
            stubs.append(f"    errno = {error};")
        if not returns_void:
            stubs.append(f"    return {fallback};")
        stubs.extend(["}", ""])
    return {INVENTORY: "[\n" + ",\n".join("  " + json.dumps(entry) for entry in inventory) + "\n]\n",
            STUBS: "\n".join(stubs)}


def symbols(root, nm, path, undefined=False):
    command = [nm, "-P", "-g"]
    command.append("--undefined-only" if undefined else "--defined-only")
    result = []
    for line in run(command + [str(path)], root).splitlines():
        fields = line.split()
        if len(fields) >= 2 and fields[0].startswith("ds4_gpu_"):
            result.append((fields[0].split("@")[0], fields[1]))
    return result


def check_link(root, objects, binary, nm):
    if not objects or not binary:
        fail("--check-link requires --objects from TCIM_OBJS and --binary")
    if len(objects) != len(set(objects)):
        fail("duplicate object in canonical TCIM link list")
    inventory = read_json(root / INVENTORY)
    by_name = {entry["symbol"]: entry for entry in inventory}
    if len(by_name) != len(inventory):
        fail("duplicate symbol in generated inventory")
    expected = {name for name, entry in by_name.items() if entry["linkage"] == "LINK_REQUIRED"}
    required = set()
    providers = {}
    for obj in objects:
        required.update(name for name, _ in symbols(root, nm, obj, True))
        for name, kind in symbols(root, nm, obj):
            if name in providers:
                fail(f"{name}: duplicate providers {providers[name]} and {obj}")
            if kind != "T" or Path(obj).name != "ds4_tcim.o":
                fail(f"{name}: provider must be a strong C function in ds4_tcim.o, got {obj} {kind}")
            providers[name] = obj
    if required != expected:
        fail(f"canonical nm -u drift: missing={sorted(expected-required)}, extra={sorted(required-expected)}")
    expected_providers = expected | {name for name, entry in by_name.items()
                                     if entry["classification"] == "IMPLEMENTED_RUNTIME"}
    if providers.keys() != expected_providers:
        fail(f"provider set drift: missing={sorted(expected_providers-providers.keys())}, "
             f"extra={sorted(providers.keys()-expected_providers)}")
    unresolved = symbols(root, nm, binary, True)
    if unresolved:
        fail(f"final unresolved GPU symbols: {unresolved}")
    linked = symbols(root, nm, binary)
    if {name for name, _ in linked} != expected_providers or any(kind != "T" for _, kind in linked):
        fail("final GPU definitions differ from the canonical strong provider set")
    print(f"TCIM link contract PASS: {len(expected)} LINK_REQUIRED, "
          f"{len(providers)} unique strong providers, no unresolved GPU symbols")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="rebuild reviewed generated files")
    action.add_argument("--check", action="store_true", help="reject AST/signature/classification drift")
    action.add_argument("--check-link", action="store_true", help="validate canonical TCIM objects and ELF using nm")
    parser.add_argument("--root", type=Path, default=ROOT, help="source root (also useful for isolated negative tests)")
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--nm", default="nm")
    parser.add_argument("--objects", nargs="+")
    parser.add_argument("--binary")
    args = parser.parse_args()
    try:
        if args.check_link:
            check_link(args.root, args.objects, args.binary, args.nm)
        else:
            for path, content in render(args.root, args.clang).items():
                if args.write:
                    (args.root / path).write_text(content)
                elif not (args.root / path).exists() or (args.root / path).read_text() != content:
                    fail(f"generated contract drift: {path}; review input/source changes, then run --write")
            print("TCIM AST contract PASS: all four declaration sources, exact signatures and explicit classifications")
    except (ValueError, OSError) as error:
        print(f"TCIM contract ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
